name: Bug Report
description: File a bug report.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Before you submit your report, make sure the bug has not already been
        reported. Also check for closed bug reports, e.g. in case it has been
        fixed in a new version.
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        Enter the output of `depreman --version` (or `npm ls depreman` as
        fallback).
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        Provide a short description of the bug. What goes wrong and when?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproducing-example
    attributes:
      label: Reproducing example
      description: |
        Provide a (minimal) scenario that triggers the bug.
      placeholder: ex. run `depreman` on the repository <https://github.com/ericcornelissen/depreman>
    validations:
      required: true
