name: Documentation
description: Report something about the documentation.
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        Report mistakes or gaps in the documentation. This can be in the docs on
        GitHub or the CLI help message.
  - type: input
    id: where
    attributes:
      label: Where
      description: |
        What piece of documentation does this concern? Include the version of
        `depreman` if relevant (you can use `npm ls depreman` for this).
      placeholder: ex. the CLI help message in v0.3.9
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: |
        Describe the problem with this documentation.
    validations:
      required: true
