name: Question
description: Ask a question.
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Ask a question if you need help using `depreman`.

        You can also use this form if you're unsure if you found a bug or if a
        feature is missing.
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        Enter the output of `depreman --version` (or `npm ls depreman` as
        fallback).
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: |
        What is your question?
    validations:
      required: true
