# MIT No Attribution
#
# Copyright 2025 Eric Cornelissen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Check
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  check:
    name: ${{ matrix.what }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        what:
          - dependencies
          - headers
          - js
          - json
          - licenses
          - lockfile
          - manifest
          - md
          - yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Check
        run: npm run "check:${WHAT}"
        env:
          WHAT: ${{ matrix.what }}
  codeql:
    name: CodeQL (${{ matrix.what }})
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload CodeQL results
    strategy:
      fail-fast: false
      matrix:
        what:
          - actions
          - javascript
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Initialize CodeQL
        uses: github/codeql-action/init@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.30.0
        with:
          config-file: ./.github/codeql.yml
          languages: ${{ matrix.what }}
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.30.0
  odgen:
    name: ODGen
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Perform ODGen analysis
        uses: ericcornelissen/odgen-action/all@c8d375a26e89a37ffad63932cbf4ae45ba990182 # v1.0.4
  mutation:
    name: Mutation test
    runs-on: ubuntu-24.04
    needs:
      - test-unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Test
        run: npm run mutation
  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Perform Semgrep analysis
        run: semgrep --sarif --output semgrep.sarif
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.30.0
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
  test-unit:
    name: Test unit
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Test
        run: npm run coverage:unit
  test-e2e:
    name: Test end-to-end (Node.js v${{ matrix.node }} with npm v${{ matrix.npm }})
    runs-on: ubuntu-24.04
    needs:
      - test-unit
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20.17.0
          - 22.9.0
          - 24.0.0
        npm:
          - 9.0.0
          - 10.0.0
          - 11.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm clean-install
      - name: Install npm@${{ matrix.npm }}
        run: npm install --global npm@${{ matrix.npm }}
      - name: Install Yarn
        run: |
          corepack enable
          yarn set version 4.1.0
      - name: Show versions
        run: |
          echo 'node --version'
          node --version

          echo 'npm --version'
          npm --version
      - name: Test
        run: npm run test:e2e
  test-os:
    name: Test OS (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    needs:
      - test-e2e
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-15
          - name: Ubuntu
            os: ubuntu-24.04
          - name: Windows
            os: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Install Yarn
        run: |
          corepack enable
          yarn set version 4.1.0
      - name: Test
        run: npm run test:e2e
